name: Validate Expo App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  expo-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Expo CLI
        run: npm install -g expo-cli

      - name: Create google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON }}" > ./google-services.json

      - name: Create Firebase Admin SDK JSON
        run: echo "${{ secrets.FIREBASE_ADMIN_SDK_JSON }}" > ./agrilease-37add-firebase-adminsdk-fbsvc-ab0f69d63a.json

      - name: Install Expo-managed dependencies
        run: npx expo install

      - name: Validate with expo doctor
        run: npx expo-doctor

      - name: Check prebuild status
        run: expo prebuild --no-install --platform android
